name: run_script

on:
  workflow_dispatch:

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
    - name: checkout repo content
      uses: actions/checkout@v3
    - name: setup python
      uses: actions/setup-python@v4
      with:
        python-version: 3.10.5
        architecture: 'x64'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: install gh cli
      shell: bash
      run: |
        curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | sudo dd of=/usr/share/keyrings/githubcli-archive-keyring.gpg
        sudo chmod go+r /usr/share/keyrings/githubcli-archive-keyring.gpg
        echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null
        sudo apt update
        sudo apt install --no-install-recommends -y gh
    - name: run script
      shell: bash
      env:
        username: ${{ secrets.USERNAME }}
        limit: ${{ secrets.LIMIT }}
        visibility: ${{ secrets.VISIBILITY }}
      run: |
        python scan_repos.py --username ${username} --limit ${limit} --visibility ${visibility}
